//--------------------------------------------------------------------------------------
// Copyright (c) 2026 BattleAxeVR. All rights reserved.
//--------------------------------------------------------------------------------------

#ifndef DEFINES_H
#define DEFINES_H

#ifdef SUPPORT_OPENXR
#undef SUPPORT_OPENXR
#endif

#ifndef SUPPORT_OPENXR
#define SUPPORT_OPENXR 0
#endif

#define SUPPORT_GAMEPADS 1

#if SUPPORT_OPENXR

#define NUM_COMMAND_BUFFERS 2
#define INVALID_INDEX -1 

#define LEFT 0
#define RIGHT 1
#define BOTH 2

#define NUM_SIDES 2
#define NUM_EYES 2
#define NUM_HANDS 2
#define NUM_CONTROLLERS 2

// OPENXR Settings

// Controller support
#define SUPPORT_KHR_SIMPLE_CONTROLLERS 0
#define SUPPORT_TOUCH_CONTROLLERS 1
#define SUPPORT_KHR_GENERIC_CONTROLLERS 0
#define SUPPORT_VIVE_CONTROLLERS 0
#define SUPPORT_VALVE_INDEX_CONTROLLERS 0
#define SUPPORT_WMR_CONTROLLERS 0

// Bindings
#define SUPPORT_AIM_POSE 1
#define SUPPORT_GRIP_POSE 1
#define SUPPORT_HAPTICS 0
#define SUPPORT_SELECT 0
#define SUPPORT_MENU 0

#define SUPPORT_THUMBSTICKS 1
#define SEPARATE_X_Y_AXES_FOR_THUMBSTICKS 1

#define SUPPORT_TRIGGERS 1
#define SUPPORT_GRIP 1
#define SUPPORT_FACE_BUTTONS 1

#define ENABLE_OPENXR_FB_REFRESH_RATE 0
#define ENABLE_OPENXR_HAND_TRACKING (USE_VR && 0)

#define ENABLE_OPENXR_FB_EYE_TRACKING_SOCIAL (USE_VR && 0)
#define ENABLE_EXT_EYE_TRACKING (USE_VR && 0)

#define SUPPORTS_BOTH_EYE_TRACKING_TYPES (ENABLE_OPENXR_FB_EYE_TRACKING_SOCIAL && ENABLE_EXT_EYE_TRACKING)
#define PREFER_EYE_TRACKING_SOCIAL_OVER_EXT (SUPPORTS_BOTH_EYE_TRACKING_TYPES && 1)

#define ENABLE_EYE_TRACKING (ENABLE_OPENXR_FB_EYE_TRACKING_SOCIAL || ENABLE_EXT_EYE_TRACKING)
#define ENABLE_EYE_TRACKING_AUTOMATICALLY (ENABLE_EYE_TRACKING && 1)

#define ENABLE_OPENXR_FB_FACE_TRACKING (USE_VR && 0)
#define ENABLE_OPENXR_FB_BODY_TRACKING (USE_VR && 0)
#define ENABLE_OPENXR_FB_SIMULTANEOUS_HANDS_AND_CONTROLLERS ((ENABLE_OPENXR_FB_BODY_TRACKING || ENABLE_OPENXR_HAND_TRACKING) && 0)

#define ENABLE_OPENXR_META_FULL_BODY_TRACKING (ENABLE_OPENXR_FB_BODY_TRACKING && 0)
#define ENABLE_OPENXR_META_BODY_TRACKING_FIDELITY (ENABLE_OPENXR_META_FULL_BODY_TRACKING && 0)

// HTC Vive Trackers / Ultimate Trackers support
#define ENABLE_VIVE_TRACKERS 0
#define ADAPT_VIVE_TRACKER_POSES (ENABLE_VIVE_TRACKERS && 1)

#define ENABLE_VIVE_HANDHELD_OBJECTS (ENABLE_VIVE_TRACKERS && 0) 
#define ENABLE_VIVE_FEET (ENABLE_VIVE_TRACKERS && 1) 
#define ENABLE_VIVE_SHOULDERS (ENABLE_VIVE_TRACKERS && 1) 
#define ENABLE_VIVE_ELBOWS (ENABLE_VIVE_TRACKERS && 1) 
#define ENABLE_VIVE_KNEES (ENABLE_VIVE_TRACKERS && 1) 
#define ENABLE_VIVE_WRISTS (ENABLE_VIVE_TRACKERS && 0) 
#define ENABLE_VIVE_ANKLES (ENABLE_VIVE_TRACKERS && 0) 
#define ENABLE_VIVE_WAIST (ENABLE_VIVE_TRACKERS && 1) 
#define ENABLE_VIVE_CHEST (ENABLE_VIVE_TRACKERS && 1) 
#define ENABLE_VIVE_CAMERA (ENABLE_VIVE_TRACKERS && 0) // Unsupported for now
#define ENABLE_VIVE_KEYBOARD (ENABLE_VIVE_TRACKERS && 0) // Unsupported for now

#define ENABLE_BODY_TRACKING (ENABLE_OPENXR_FB_BODY_TRACKING || ENABLE_VIVE_TRACKERS)
#define ENABLE_WAIST_TRACKING (ENABLE_BODY_TRACKING && 1)

#define LOG_EYE_TRACKING_DATA (ENABLE_OPENXR_FB_EYE_TRACKING_SOCIAL && 0)
#define LOG_BODY_TRACKING_DATA (ENABLE_OPENXR_FB_BODY_TRACKING && 0)


#endif // SUPPORT_OPENXR

#endif // DEFINES_H